# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - APP-Java11SpringBootMaven-Win-AiV3Sdk01-JPE

on:
  push:
    branches:
      - v3sdk
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Rename app jar
        run: mv '${{ github.workspace }}/target/*.jar' '${{ github.workspace }}/app.jar'

      - name: Download Application Insights agent
        run: Invoke-WebRequest -Uri https://github.com/microsoft/ApplicationInsights-Java/releases/download/3.4.7/applicationinsights-agent-3.4.7.jar -OutFile applicationinsights-agent-3.4.7.jar -PassThru

      - name: Zip files
        run: Compress-Archive -Path '${{ github.workspace }}/app.jar','${{ github.workspace }}/applicationinsights-agent-3.4.7.jar' -DestinationPath '${{ github.workspace }}/pack.zip'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app-zip
          path: '${{ github.workspace }}/pack.zip'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app-zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'APP-Java11SpringBootMaven-Win-AiV3Sdk01-JPE'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_648433FB3B9140C3B8EB694194AAD98B }}
          package: 'pack.zip'
